### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by zhaiqing** [supersyq/RIENet#1]
Hello, I am very interested in your work, Can you open this code？ thank you

**Comment by supersyq** [comment]
> Hello, I am very interested in your work, Can you open this code？ thank you

Thank you for your interest. We are currently working on preparing our code and we will release it on 31/03/2022.

**Comment by zc6189** [comment]
Hi, I am very interested in your work, will your code be open today?

**Comment by OVEYA123** [comment]
I'm more curious about some implementation details in the article, looking forward to your open source code
