### ISSUE TITLE
有关论文对比方法-RPM-Net在kitti数据集上的结果

### ISSUE THREAD

**Issue by Dlemand** [supersyq/RIENet#2]
请问这个数据是哪里得到的，还是您自己跑的。谢谢

**Comment by supersyq** [comment]
> 请问这个数据是哪里得到的，还是您自己跑的。谢谢

我自己跑哒！

**Comment by Dlemand** [comment]
您好，打扰一下。请问你您如何算出Kitty_list中存放的Tr数据，我自己根据kitty数据集中的pose数据算了一下，结果不太正确。
谢谢！

**Comment by supersyq** [comment]
> 您好，打扰一下。请问你您如何算出Kitty_list中存放的Tr数据，我自己根据kitty数据集中的pose数据算了一下，结果不太正确。 谢谢！

使用的是HRegNet的kitti_list!

**Comment by supersyq** [comment]
你好，我是将hregnet这篇论文的代码里面的list拿过来使用的。


--------------原始邮件--------------
发件人："Dlemand ***@***.***&gt;;
发送时间：2022年7月22日(星期五) 下午5:39
收件人："supersyq/RIENet" ***@***.***&gt;;
抄送："沈雅琦 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [supersyq/RIENet] 有关论文对比方法-RPM-Net在kitti数据集上的结果 (Issue #2)
-----------------------------------

 

 
您好，打扰一下。请问你您如何算出Kitty_list中存放的Tr数据，我自己根据kitty数据集中的pose数据算了一下，结果不太正确。
 谢谢！
