### ISSUE TITLE
Confusion about the PRNet cropping

### ISSUE THREAD

**Issue by ZhileiChen99** [supersyq/RIENet#3]
The paper says that the cropping setting is the same as PRNet cropping, but from the source code, I find that you just choose the first 768 points, which is different from PRNet cropping. Could you tell me why you use this setting?

**Comment by supersyq** [comment]
Hi,&nbsp;we used the ''farthest_subsample_points'' function in PRNet to crop the point clouds of ModelNet40 dataset in our code. Please check it again.

--------------原始邮件--------------
发件人："ZhileiChen ***@***.***&gt;;
发送时间：2022年10月6日(星期四) 上午10:42
收件人："supersyq/RIENet" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[supersyq/RIENet] Confusion about the PRNet cropping (Issue #3)
-----------------------------------

 

 
The paper says that the cropping setting is the same as PRNet cropping, but from the source code, I find that you just choose the first 768 points, which is different from PRNet cropping. Could you tell me why you use this setting?

**Comment by ZhileiChen99** [comment]
It is my carelessness. Thank you.
